analytics:
  twitter: null
  google: UA-29693279-1
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.2489362
  brandStrength: 0.1191489
  lightness: 0.5319149
  brandColors:
    - '#181E1E'
    - '#6F9AD7'
    - '#657788'
    - '#C68A6D'
    - '#B4C64B'
  rhythmicContrast: 0
typography_spectrum: 0.2765957
layout_spectrum: 0.7446808
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: MFA not MBA
